table=[
"32 32 111 2 ",
"   c None",
".  c #6E7D82",
"X  c #6E7D83",
"o  c #6E7E83",
"O  c #6F7E83",
"+  c #6F7F84",
"@  c #707F84",
"#  c #738287",
"$  c #748388",
"%  c #758388",
"&  c #748489",
"*  c #768489",
"=  c #768589",
"-  c #75858A",
";  c #76868B",
":  c #78868B",
">  c #78888D",
",  c #7A888C",
"<  c #7E8B8F",
"1  c #7A8A90",
"2  c #7C8C91",
"3  c #7D8D93",
"4  c #7D8E93",
"5  c #7E8E94",
"6  c #808D91",
"7  c #808D92",
"8  c #818E92",
"9  c #828F93",
"0  c #819297",
"q  c #859196",
"w  c #879398",
"e  c #85969B",
"r  c #86979C",
"t  c #899599",
"y  c #8A969A",
"u  c #87989D",
"i  c #86989E",
"p  c #87999E",
"a  c #87999F",
"s  c #88999F",
"d  c #8D999D",
"f  c #899AA0",
"g  c #899BA0",
"h  c #8B9DA2",
"j  c #8C9EA3",
"k  c #8C9EA4",
"l  c #8DA0A5",
"z  c #8EA0A6",
"x  c #8EA1A6",
"c  c #8FA2A8",
"v  c #98A2A6",
"b  c #99A4A7",
"n  c #90A3A9",
"m  c #91A3A9",
"M  c #91A4AA",
"N  c #92A5AB",
"B  c #9AA4A8",
"V  c #9AA5A8",
"C  c #9BA5A9",
"Z  c #9CA7AA",
"A  c #9DA7AA",
"S  c #9EA8AC",
"D  c #9FA9AC",
"F  c #9FA9AD",
"G  c #A1AAAD",
"H  c #A3ADB0",
"J  c #A4ADB0",
"K  c #A5AEB1",
"L  c #A5AFB2",
"P  c #A6AFB2",
"I  c #A7B0B3",
"U  c #A8B1B4",
"Y  c #ACB5B8",
"T  c #ADB5B8",
"R  c #AFB7BA",
"E  c #B0B8BB",
"W  c #B1B9BC",
"Q  c #BCC3C5",
"!  c #BDC4C6",
"~  c #C1C7C9",
"^  c #C9CFD0",
"/  c #CED3D5",
"(  c #D0D4D6",
")  c #D1D5D7",
"_  c #D7DBDC",
"`  c #D9DDDE",
"'  c #DADEDF",
"]  c #DBDFE0",
"[  c #DFE2E3",
"{  c #E1E4E5",
"}  c #E3E5E6",
"|  c #E6E8E9",
" . c #E8EBEB",
".. c #EAECED",
"X. c #EBEDEE",
"o. c #ECEEEF",
"O. c #EDEFEF",
"+. c #EEF0F0",
"@. c #EEF0F1",
"#. c #F2F4F4",
"$. c #F4F5F6",
"%. c #F5F6F6",
"&. c #F5F6F7",
"*. c #F6F7F7",
"=. c #F9F9FA",
"-. c #F9FAFA",
";. c #FAFAFB",
":. c #FBFBFB",
">. c #FBFCFC",
",. c #FDFDFD",
"<. c white",

"              N N N N N N N N N N N N N N N N l                 ",
"            N N N N N N N N N N N N N N N N N l .               ",
"            N N N N N N N N N N N N N N N N N l . . .           ",
"            N N N N N N N N N N N N N N N N N l . . . .         ",
"            N N N N N N N N N N N N N N N N N l . . . . .       ",
"            N N N N N N N N N N N N N N N N N N + . . . . .     ",
"            N N N N N N N N N N N N N N N N N N i . . . . . .   ",
"            N N N N N N N N N N N N N N N N N N N k > ; ; ; ; ; ",
"            N N N N N N N N N N N N N N N N N N N N N k r r r r ",
"            N N N N N N N N N N N N N N N N N N N N N N c f r r ",
"            N N N N N N N N N N N N N N N N N N N N N N N N l i ",
"            N N N N N N N N N N N N N N N N N N N N N N N N N n ",
"            N N N N N N N N N N N N N N N N N N N N N N N N N N ",
"            N N N N N N N N N N N N N N N N N N N N N N N N N N ",
"            N N N N N N N N N N N N N N N N N N N N N N N N N N ",
"    . . . + 3 3 3 3 3 3 3 3 4 4 4 4 4 4 3 3 3 3 3 5 i N N N N N ",
". . . . . . . . . . . @ . . . . . . . . . . . . . . . 0 n N N N ",
". . Z , . . v < t B Z Z Z 8 q b $ . q V ; ; Z . . . . $ r j n N ",
". . %.L . . ..T ! ' %.X.' I ' <.I . ] <.L D :.. . . . $ r r i l ",
". . %.G . . ..T . . ' ! . . ' +.) $ >.+.L D :.. . . . $ r r r r ",
". . %.:.$.$.,.T . . ' ! . . ' ^ *.Z | } I D :.. . . . $ r r r r ",
". . %.R 6 6 X.T . . ' ! . . ' E #.} ~ [ L D :.. . . . $ r r r r ",
". . %.J . . ..T . . ' ! . . ' R / <.V } L D :.t t w . $ r r r r ",
". .  .v . . { G . . ( R . . ) G D $.; _ Z d ....X.X.8 $ r r r r ",
". . . . . . . . . . . . . . . . . . . . . . . . . . . % e r r r ",
". . . . . . . . . . . . . . . . . . . . . . . . . . . 3 e r r r ",
"    . . . . > ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; 3 e r r r r ",
"            N l s e e r e e e e e e e e e e r r r r e e r r r r ",
"            N N N j e e r r r r e r r r r r r r r r r r r r r r ",
"            N N N N n s r r r r e r r r r r r r r r r r r r r r ",
"            N N N N N N k r r r r r r r r r r r r r r r r r r r ",
"              N N N N N N n f r r r r r r r r r r r r r r r r   "
]
